name: gcn
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py36h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.2.0=py36he98fc37_0
  - pip=21.1.2=py36h06a4308_0
  - python=3.6.12=hcff3b4d_2
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.7.0=py36_cu102
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - backcall==0.2.0
    - cached-property==1.5.2
    - chardet==4.0.0
    - click==8.0.1
    - cycler==0.10.0
    - dataclasses==0.8
    - decorator==4.4.2
    - filelock==3.0.12
    - future==0.18.2
    - googledrivedownloader==0.4
    - h5py==3.1.0
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==4.5.0
    - ipdb==0.13.9
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - isodate==0.6.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - networkx==2.5.1
    - nltk==3.5
    - numba==0.53.1
    - packaging==20.9
    - pandas==1.1.5
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plyfile==0.7.4
    - prompt-toolkit==3.0.19
    - ptyprocess==0.7.0
    - pygments==2.9.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - python-louvain==0.15
    - pytz==2021.1
    - pywavelets==1.1.1
    - rdflib==5.0.0
    - regex==2021.4.4
    - requests==2.25.1
    - sacremoses==0.0.45
    - scikit-image==0.17.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - sentencepiece==0.1.94
    - threadpoolctl==2.1.0
    - tifffile==2020.9.3
    - tokenizers==0.8.1rc2
    - toml==0.10.2
    - torch==1.9.0+cu111
    - torch-cluster==1.5.9
    - torch-geometric==1.7.1
    - torch-scatter==2.0.7
    - torch-sparse==0.6.10
    - torch-spline-conv==1.2.1
    - tqdm==4.55.1
    - traitlets==4.3.3
    - transformers==3.1.0
    - typing-extensions==3.10.0.0
    - urllib3==1.26.5
    - wcwidth==0.2.5
    - zipp==3.4.1
prefix: /usr0/home/yitingye/miniconda3/envs/gcn
